.TH "FB2totxt User Manual" 0.20180717 "17 Jul 2018" "User documentation"

.SH NAME
fb2encode

.SH DESCRIPTION
Bash-script for console FB2 encode

.SH SYNOPSIS
fb2encode [options] book.fb2

.SH OPTIONS
.TP
-c str
dest code (default = utf-8)
.TP
-o name.fb2
name encode file (default = source file)
.TP
-h
help

.SH EXAMPLE
 fb2encode youbook.fb2
 fb2encode -c koi8-r youbook.fb2

.SH COPYRIGHT
 Copyright 2018 zvezdochiot.
 All rights reserved.

.SH SEE ALSO
 fb2totxt,
 fb2tozip,
 grep,
 sed,
 iconv

.SH CONTACTS
 Website: https://github.com/zvezdochiot/bash-fb2
 Email: zvezdochiot@users.sourceforge.net
