.TH "FB2totxt User Manual" 0.20180819 "19 Aug 2018" "User documentation"

.SH NAME
fb2toinfo

.SH DESCRIPTION
Bash-script for console FB2 info reader

.SH SYNOPSIS
fb2totxt [options] book.fb2

.SH OPTIONS
.TP
-a
list authors (default = false)
.TP
-c
list content (default = false)
.TP
-o name.txt
name text file (default = stdout)
.TP
-z
force unzip (default = false)
.TP
-h
help

.SH EXAMPLE
 fb2toinfo book.fb2.zip

.SH COPYRIGHT
 Copyright 2018 zvezdochiot.
 All rights reserved.

.SH SEE ALSO
 fb2encode,
 fb2totxt,
 fb2tozip,
 fb2xmlfix,
 sed,
 file,
 less,
 unzip,
 zcat

.SH CONTACTS
 Website: https://github.com/zvezdochiot/bash-fb2
 Email: zvezdochiot@users.sourceforge.net
