.TH "FB2totxt User Manual" 0.20180717 "17 Jul 2018" "User documentation"

.SH NAME
fb2tozip

.SH DESCRIPTION
Bash-script for console FB2 pack/unpack

.SH SYNOPSIS
fb2tozip [options] book.fb2

.SH OPTIONS
.TP
-d
decompress book
.TP
-o str
name pack/unpack file (default = [source.fb2].zip/[source].fb2)
.TP
-h
help

.SH EXAMPLE
 fb2tozip youbook.fb2
 fb2tozip -d youbook.fb2.zip

.SH COPYRIGHT
 Copyright 2018 zvezdochiot.
 All rights reserved.

.SH SEE ALSO
 fb2encode,
 fb2totxt,
 unzip,
 zip

.SH CONTACTS
 Website: https://github.com/zvezdochiot/bash-fb2
 Email: zvezdochiot@users.sourceforge.net
