.TH "FB2totxt User Manual" 0.20180725 "25 Jul 2018" "User documentation"

.SH NAME
fb2xmlfix

.SH DESCRIPTION
Bash-script for console FB2 fix

.SH SYNOPSIS
fb2xmlfix [options] book.fb2

.SH OPTIONS
.TP
-o str
name fix book (default = source.fb2)
.TP
-h
help

.SH EXAMPLE
 fb2xmlfix youbook.fb2
 fb2xmlfix -o youbook-fix.fb2 youbook.fb2

.SH COPYRIGHT
 Copyright 2018 zvezdochiot.
 All rights reserved.

.SH SEE ALSO
 fb2encode,
 fb2totxt,
 fb2tozip,
 xmlstarlet

.SH CONTACTS
 Website: https://github.com/zvezdochiot/bash-fb2
 Email: zvezdochiot@users.sourceforge.net
